### ISSUE TITLE
번호에 하이픈(-) 입력 방지코드 추가 또는 README수정

### ISSUE THREAD

**Issue by darron1217** [Bumkeyy/sens#1]
번호에 하이픈(-)이 들어가면 Bad Request라고 나옵니다

README 예제에는 하이픈이 들어가있어서 헷갈릴듯 합니다

좋은 패키지 만들어주셔서 감사합니다 👍

**Comment by bumkeyy** [comment]
@darron1217 
아 README에 충분히 헷갈릴만한 요소가 있었네요.
리포트 감사합니다! :)

**Comment by bumkeyy** [comment]
README에 수정했습니다.

해당 이슈는 close 하겠습니다 :)
