### ISSUE TITLE
NCPClient를 전역으로 설정해두고 오래 사용하니 unauthorized에러 발생

### ISSUE THREAD

**Issue by darron1217** [Bumkeyy/sens#2]
`new NCPClient()`로 인스턴스를 생성하여 전역변수로 지정하고 사용중입니다.

처음엔 발송이 잘 되다가 몇시간후부터 `unauthorized`에러가 발생하는데, 왜 그런건지 메세지가 구체적이지 않아 원인을 잘 모르겠습니다.

추정으로는 `timestamp`변수와 연관된것 같은데, timestamp는 construct시점이 아닌, send시점에 생성되어야 하는게 아닐지 궁금합니다

**Comment by darron1217** [comment]
https://apidocs.ncloud.com/ko/ai-application-service/sens/sms_v2/#api-header
Timestamp 때문이 맞는것 같네요 5분제한 되어있네요ㅎ
제가 PR을 올려볼까요?

**Comment by bumkeyy** [comment]
> https://apidocs.ncloud.com/ko/ai-application-service/sens/sms_v2/#api-header
> Timestamp 때문이 맞는것 같네요 5분제한 되어있네요ㅎ
> 제가 PR을 올려볼까요?

넵! 그럼 감사하겠습니다 😄

**Comment by darron1217** [comment]
@Bumkeyy PR올렸습니다 확인부탁드릴께요 :)

**Comment by bumkeyy** [comment]
@darron1217 

v1.3.0에 적용됬습니다.

감사합니다 👍
